version: "3.7"
services:
  build:
    image: node:lts-alpine
    command: sh -c "npm ci --production && npm run build"
    working_dir: /app
    volumes:
      - ./:/app
  app:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./build:/usr/share/nginx/html:ro
    depends_on:
      - build
